### ISSUE TITLE
IP defaults to local IP when hosting

### ISSUE THREAD

**Issue by kazinium** [Novetus/Novetus_src#10]
When hosting, the IP the server wants to use defaults to my local machine IP, is there anywhere I can change this because I can't seem to do it within the client.

**Comment by Bitl** [comment]
It doesn't default to your local machine IP. It will host on your public IP unless you haven't enabled UPnP or port forwarded. The IP option is only for joining servers, not creating them. If you want to share your server information, go to the Host tab.

**Comment by kazinium** [comment]
I am on the host tab, I am not entirely sure why but the IP address under server information is my machine IP, i tried toggling UPnP and that didn't change anything I am unsure how I am supposed to port forward like this.

**Comment by Bitl** [comment]
It should just be on your public IP

**Comment by LeontKing2** [comment]
Novetus is Based on UDP Portforwarding heres a tutuorial https://itch.io/t/1396743/tutorial-on-getting-a-hostname-with-ssh-portforward-i-think-using-playitgg

**Comment by LeontKing2** [comment]
Also you can change the ip with the AlternateServerIP thing in configs/config.txt or smth https://github.com/Novetus/Novetus_src/issues/22

**Comment by Bitl** [comment]
i believe the reason this happens is because the server is not port forwarded or upnp is not enabled. please port forward the port in the host tab or enable upnp (assuming that upnp is enabled on your router)
