### ISSUE TITLE
WMVCore.dll is missing

### ISSUE THREAD

**Issue by ProNicoY** [Novetus/Novetus_src#19]
This isn't a bug. I can't use 2011 versions. it keep saying "WVMCore.dll is missing, but when I go to "system32 folder" there is WVMCore.dll. Did I put the WVMCore.dll in the wrong folder?

Sorry if my English is bad.

**Comment by Bitl** [comment]
Try installing this and see if it works for you.

https://www.microsoft.com/en-us/software-download/mediafeaturepack

**Comment by ProNicoY** [comment]
Thanks for the help, I'll try that out

**Comment by ProNicoY** [comment]
I didn't found my Windows version. and then i tried searching on google and
this is what i found:


   - Open *Windows* Settings and go to Apps.
   - Under Apps & *Features*, click on Optional *features*. Apps *Features*
    1.
   - Click on Add a *feature*. Add a *feature*.
   - Find *Media Feature Pack* from the list.
   - Clicking on the item will enable the *Install* button.


I tried doing it, but when i installed the media feature pack, it
didn't show up in my optional features. If you need my windows version here
it is: My windows is windows 7 and then i upgraded it into windows 10 ver
1909

**Comment by dfault-user** [comment]
If you use "Windows Server" or any "N" edition of Windows, you will most likely need the Windows Server Essentials role or the Windows Media Feature Pack. It does NOT show in your optional features, it just bolts itself into your current Windows install.
