### ISSUE TITLE
New clients (2012,2013,2014)

### ISSUE THREAD

**Issue by catboxed** [Novetus/Novetus_src#20]
It'd be nice if there were 2012-2014 clients, as i am trying to reupload my game onto Novetus after the shutdown of Finobe, where my building game first took off.

My game was running on Finobe's 2012 client, and the game had terrain, which none of Novetus' clients support, which isn't very pleasnt.

I hope the clients will be added, it will not only help me but dozen other people as they have also wanted a 2012 client.
2013 and 2014 are just neat, they are inbetween the classic roblox to modern roblox transition. I'd like to have them aswell.

Thanks!!!

**Comment by garyiguess** [comment]
n̴̢̢̡̛̰̲̺̰̱̱͖̗̥̼͈̔̉̐̐̍̒̓̄͛͑͝ͅö̶̧͇̠̫̟̖́͒͗̀̀͊́̈́̕͝v̸̛͕͔̀̎͛̔̎̓̒̆̑̾̀͊̅͠͝͠ę̴̢̨̩̟̰̙̬̮̥̤̱̺̊̉̊̊̄̔̏͛͘ͅt̷̢̛̛̲̘̳̻͖̝̝̗̙̻̖̅͛̃̏̾̿̓̐̓̀͘u̶̪̲̫̓͋͒̔s̶̫̀̍̒̉̇̅͊͌̓̌̈́͝͝͝ ̷̛̛͓͇͚̘̭͚̐͂̀̇͜a̴̯̪͇̻̟̝͋̔́̆̈́̽̈́̒̀̒̽̚̚͠d̷̩̥̱̥̳̫̰̱͇̣͕̤͎͕̒̈́͛͊̍́̃͗̆̊͜ͅͅd̷̻̪̣̫̤̪̠̰̺̹͆̾͌̇̓̓͛͗̿̏͛̕͠͝ ̶̣̙̤̳̪̗̭̞́̈́ĭ̸̡̡̧̳̱̪̬͎̤̥̦̱̗̩͓ṱ̷͓͎̼̻̑̑̏̆͐̀̽̊͗̄̇ ̵̼̳̦͒́̂̅͊̂́̐̽͗̚n̴̡̖͔͖̪̯̲̲̒͆̑̅̈́̽̏̅͐͊̾̅̅̚͝͠ò̵͉̰͓̤̯̙͓̣̟̙͇̲̭w̵̨͎̖̳̻̦̝̪͊̆̅

**Comment by alex9997979z** [comment]
even though you could use a mod for that
but its complex as fuck to do that

**Comment by Bitl** [comment]
These won't be added officially in the near future

**Comment by catboxed** [comment]
> These won't be added officially in the near future
> 
> the reasoning is because these are complex clients that are beyond my current patching skills. I recommend looking for mods like what @alex9997979z said.

awh, there were mods like novetus+ or novetuslabs but they either got privated or just entirely shut down. Alright then, thanks!

**Comment by alexvankman** [comment]
no more mods apart from austiblox and that banned me

**Comment by IDeletedSystem64** [comment]
a 2012 client is available in the latest snapshots (2012M) and newer clients unfortunately can't work with Novetus at the moment as they require online assets, You will need Sodikm for newer clients
