### ISSUE TITLE
2009E-HD has no sky

### ISSUE THREAD

**Issue by SomeDudeOnGithub** [Novetus/Novetus_src#21]
When you load any map in the 2009E-HD client, the sky just turns completely white.
![2009](https://user-images.githubusercontent.com/80745237/121409655-6a2d4480-c96a-11eb-8993-5bd39a2a5ccc.png)

**Comment by catboxed** [comment]
check your client skybox textures, try reinstalling the client with the antivirus turned off. If still not fixed then it's either a bug in the modified HD client

**Comment by SomeDudeOnGithub** [comment]
I've checked the skybox texture files, they're there, i've reinstalled the client with my antivirus off, sky's still missing. I am positive this is a bug in the client, every other client except for 2009E-HD have skies.

**Comment by SomeDudeOnGithub** [comment]
Problem fixed by removing spaces in folder path.

**Comment by SomeDudeOnGithub** [comment]
I was going to report more problems but they were all also fixed when i removed the spaces.
