### ISSUE TITLE
How does novetus generates Online novetus:// Links So We can change the ip of the novetus:// link which redirects to the server

### ISSUE THREAD

**Issue by LeontKing2** [Novetus/Novetus_src#22]

**Comment by mallgrab** [comment]
Download the repository and search for it since github's search engine isn't good for searching through code.
It combines 'localhost' with the client version and port and encodes it as a base64 string.

**Comment by LeontKing2** [comment]
i dont even get how to do tht lol

**Comment by LeontKing2** [comment]
so how to convert alphabets to base64 string

**Comment by LeontKing2** [comment]
like playit.gg:123123

**Comment by LeontKing2** [comment]
@Bitl  can you help ?

**Comment by Bitl** [comment]
Edit "AlternateServerIP" in the ini file for the uri to use your desired IP address

**Comment by LeontKing2** [comment]
Ohk

**Comment by LeontKing2** [comment]
Thanks :D

**Comment by LeontKing2** [comment]
> Edit "AlternateServerIP" in the config/config.ini file for the uri to use your desired IP address
> 
> then you can use the normal uri for your link

wait how to edit that ?

**Comment by LeontKing2** [comment]
it is always changing back to localhost

**Comment by LeontKing2** [comment]
nvm it works

**Comment by LeontKing2** [comment]
#10 Please read this the above to change it to something else
