### ISSUE TITLE
Client EXTREMELY slow/laggy?

### ISSUE THREAD

**Issue by tonumber** [Novetus/Novetus_src#25]
Character moves very slow and laggily,
didnt happen with the old version (RbxLegacy)
Any solutions? 
Also when first running, the .nov file isnt created.

**Comment by biggerbraintime** [comment]
if you're playing anything before 2010, of course its laggy. they all have horrible performance and bad optimizations.

**Comment by Bitl** [comment]
All clients before 2009 have issues with slowdown. As far as I know this cannot be fixed.
