### ISSUE TITLE
Clients 2010L and newer cause "Your graphics drivers seem to be too old for Roblox to use" error when launched from launcher in Wine

### ISSUE THREAD

**Issue by man-of-eel** [Novetus/Novetus_src#26]
Running the executables when inside their directories works, for example:
`/mnt/sda1/Games/Novetus/clients/2011M$ wine start RobloxApp_studio.exe` works while
`/mnt/sda1/Games/Novetus$ wine start clients/2011M/RobloxApp_studio.exe` gives the error.

I suspect this is related to the RenderSystem DLLs (RenderSystem_Direct3D9.dll and RenderSystem_GL.dll) not being included properly, but that's just a guess. Probably an easy fix but I'm not too knowledgeable to try and fix it myself.

**Comment by LeontKing2** [comment]
Yeah

**Comment by LeontKing2** [comment]
we can do a very easy fix

>

**Comment by man-of-eel** [comment]
Log file (opening studio, clicking New and exiting): https://pastebin.com/enh5qV4n
https://pastebin.com/4LfuAX12 longer log without some debugs disabled

**Comment by man-of-eel** [comment]
Made a quick patch, should work #27
