### ISSUE TITLE
failed to connect (id=14) problem

### ISSUE THREAD

**Issue by dominoeslogic64** [Novetus/Novetus_src#38]
anyone issue this problem by just opening the play button?
i mean the play solo one works but the play button doesn't work, do anyone also issue this? and if so, has anyone got help for this identification problem?
![Снимок экрана 2022-01-21 200042](https://user-images.githubusercontent.com/98181482/150577384-2c03b906-99f0-41c2-b572-35bf98238a1e.png)

**Comment by Luke18033** [comment]
That's the "join server" button, there needs to be a server running at the specified IP/port for it to connect

**Comment by Bitl** [comment]
server-related issue

**Comment by Niko1asGit** [comment]
yea am having the same issue
