### ISSUE TITLE
Possible https://www.roblox.com/asset/?id= decal issue???????

### ISSUE THREAD

**Issue by zensemic59** [Novetus/Novetus_src#41]
In 2007m it doesn't show any https://www.roblox.com/asset/?id= file(s) here

**Comment by FlashlightET** [comment]
same here

**Comment by Bitl** [comment]
link is down

**Comment by subad31155** [comment]
> link is down

Think, that its so problem when opening 2008 - RoTris, assets have been broken, as a link is down.
