### ISSUE TITLE
[COMPATIBILITY] Add Arm64 Build Support

### ISSUE THREAD

**Issue by LeontKing2** [Novetus/Novetus_src#44]

**Comment by LeontKing2** [comment]
apparently Microsoft made a arm64 version of windows11 that supports 32-bit programs Without any issues like they just run

**Comment by LeontKing2** [comment]
since all clients in novetus is 32 bit so yea

**Comment by Bitl** [comment]
no, arm will not be natively supported as the net framework 4.0 is not natively supported.

novetus should load fine in arm with net framework as x86 support continues to develop for ARM windows
