### ISSUE TITLE
2011M: mouse jumps all over the place

### ISSUE THREAD

**Issue by TheAwesome98-Real** [Novetus/Novetus_src#45]
trying to move around using the green circle or click any hud-icons causes the mouse to spaz all over the place. this causes the game to be extremely difficult to play.

**Comment by TheAwesome98-Real** [comment]
reproduced on 2011E

**Comment by TheAwesome98-Real** [comment]
cannot be repro'd on 2008M

**Comment by TheAwesome98-Real** [comment]
not on 2009-HD either

**Comment by TheAwesome98-Real** [comment]
can repro on 2010L

**Comment by Bitl** [comment]
This is an issue mainly with VM or Wine settings.

**Comment by TheAwesome98-Real** [comment]
I'm using wine. any configs that can fix it?
