### ISSUE TITLE
2007M client doesn't let me make servers

### ISSUE THREAD

**Issue by dominoeslogic64** [Novetus/Novetus_src#47]
tried using 2007M but when i start a server, it doesn't let me and just shows up an error, however when i use other clients like 2008M, it works, any way i can fix this issue?

https://user-images.githubusercontent.com/98181482/188706959-a1f620a7-42ac-47f4-ae1a-f9dfc30f37ac.mp4

**Comment by Bitl** [comment]
Install the Visual C++ 2005 Redistributable. This is provided with Novetus in the _redist folder and can be installed through the Dependency Installer as well.
