### ISSUE TITLE
Compatibility with older Windows versions

### ISSUE THREAD

**Issue by tomrow** [Novetus/Novetus_src#5]
Would it be possible to make a version of the launcher that works with older versions of Windows, like XP?
Running older versions of Roblox with Windows XP would be ultimate nostalgia for me.

**Comment by Bitl** [comment]
Novetus as of 1.2 and up runs natively on windows XP, with a few things you need to consider first. You can find this info here: https://bitl.itch.io/novetus/devlog/161722/12-day-one

**Comment by tomrow** [comment]
Thanks! The last version I used was 1.0.0 so I didn't know about this feature.
