### ISSUE TITLE
2012M: Where's the Roblox Studio button?

### ISSUE THREAD

**Issue by FredCentre** [Novetus/Novetus_src#57]
Novetus 1.3 Snapshot v22.8412.32591.1: I testing play Crossroad with 2012M client, but I can't close Roblox Studio. Please fix this!

**Comment by Bitl** [comment]
I don't understand what the issue is. Can you be a bit more descriptive?

**Comment by FredCentre** [comment]
Um, I mean: I mean: I don't see a button on the screen to turn off Roblox Studio in 2012M

**Comment by Bitl** [comment]
It shows up within a minute or so. Closed.
