### ISSUE TITLE
Some bugs with the latest snapshot (23.8544.14774.1)

### ISSUE THREAD

**Issue by MattRTGB** [Novetus/Novetus_src#63]
Regen ID doesn't work, and joining a game doesn't work either.
I don't think that this is a problem with my PC because the previous snapshot works just fine and also all the other versions do.
![image](https://github.com/Novetus/Novetus_src/assets/84507847/ab7e6be9-5c7b-407f-a708-de7e8627595e)

**Comment by Bitl** [comment]
This has been partially fixed. Regen ID is still broken as of the latest snapshot.

**Comment by Bitl** [comment]
Forgot to close this as regen id has been fixed.
