### ISSUE TITLE
Unable to Save when Using Studio

### ISSUE THREAD

**Issue by Arbanon-Epsilon** [Novetus/Novetus_src#64]
Hi,

Currently unable to save my changes when using the studio, both on Linux and Windows. Any changes will simply be reverted upon reloading the map file. However, saving does work when using "Save As".

- Client/Studio: 2011M
- OS: Fedora 38, Linux 6.3.8
- Wine Version: 8.6 Staging
**AND**
- OS: Windows 10 LTSC

**Comment by Bitl** [comment]
Saving may take multiple tries before it saves the file. This is a client issue that i don't think is fixable currently
