### ISSUE TITLE
Cursor Stuck on Studio and Game View Screen

### ISSUE THREAD

**Issue by Lambda-Epsilon** [Novetus/Novetus_src#65]
As the title says, cursor is stuck. If you move the mouse a great distance, it will eventually just slide into the explorer, etc and you'll be able to use it until you go over the game again, at which point it will be stuck. This was not the case moments ago, but all of a sudden has begun happening.

![image](https://github.com/Novetus/Novetus_src/assets/81492567/aea16946-b4b0-432f-aacb-b5d43701318c)

- Client/Studio: 2011M
- OS: Fedora 38, Linux 6.3.8
- Wine Version: 8.6 Staging
**AND**
- OS: Windows 10 LTSC

**Comment by Bitl** [comment]
I do not offer support for novetus versions that are not the current stable or snapshot versions.

On linux, run Novetus under Bottles for the best experience.
