### ISSUE TITLE
Cannot connect to any server nor Play Solo

### ISSUE THREAD

**Issue by KorbynTalks** [Novetus/Novetus_src#69]
**This was found in the Snapshot.**

So I tried to play my friend's server but it gave me the error "Failed to connect to the Game."
I tried every solution I could think of, Restarting my PC, reinstalling Novetus, and Playing Solo did not help either it would just put me into Roblox Studio, Resetting my config, Changing version, And other possible fixes that led to no avail.
The versions I tried are 2012M, and 2011E.

I decided to put up this issue as it bothers me, I've been troubleshooting for hours and was starting to lose my sanity.
I hope you'll be able to fix this.

oh, and a small thing. I just tried 2010L and it connected just fine. I have no clue what is going on at this point.

**Comment by Bitl** [comment]
This sounds like more of a server hosting issue, make sure ports or forwarded or you use a tunneling software like playit.gg. Other than that I can't offer support since I haven't hosted any servers.
