### ISSUE TITLE
Roblox client crashes upon opening with message "Failed to open document"

### ISSUE THREAD

**Issue by bycreatinganaccountyou** [Novetus/Novetus_src#70]
OS: Linux Mint 21.2
I can open the Novetus launcher just fine, but when I try to open a map on any version I get an error "Failed to open document" and the client closes. I tried it on both wine stable(9.0.0) and Staging (9.8.0), as well as Bottles, but nothing worked.
![hfghjdfgdsfgsdfg](https://github.com/Novetus/Novetus_src/assets/167011547/1734d02b-d899-40a6-9bf3-d2fb7c7ab964)
Edit: The problem seems to be with opening .rbxl files. I can open the studio just fine if I open it empty, I also downloaded MaximumADHD's 2007 roblox and I could interact with the studio just fine but I couldn't open places and if i tried saving them it wouldn't say anything was wrong but wouldn't save them either.

**Comment by Bitl** [comment]
Make sure Novetus is not installed in a path that has spaces in it.
