### ISSUE TITLE
Error joining or starting server

### ISSUE THREAD

**Issue by RicardoGamerTVDev** [Novetus/Novetus_src#9]
Everytime I try to start a server or join a server on the launcher using buttons "JOIN SERVER" and "START SERVER", The studio application opens up, but I get an error saying "The permeator is incorrect". Anyone know how to fix it? Really want to play some old ROBLOX games with my cousin.

**Comment by Bitl** [comment]
Try selecting a different map or place Novetus in the root of your drive (example: c:/)

**Comment by RicardoGamerTVDev** [comment]
I've placed Novetus in my C:\ driver, and tried different maps, nothing has changed. Maybe I need to install dependencies?

**Comment by RicardoGamerTVDev** [comment]
Nevermind, all working now. Just needed to run the admin launcher.

**Comment by LeontKing2** [comment]
> Edit: Was working once, then stopped working and want's to say the same error again.

I think this is solvable go to your taskmanager and right click on any tab like name or stuff then enable command line youll be able to see how the program has started by a command and then paste the command here
